apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keel.fullname" . }}
  labels: {{- include "keel.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "keel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "keel.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "keel.fullname" .) }}
      containers:
        - name: keel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
            - configMapRef:
                name: {{ include "keel.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
