apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "keel.fullname" . }}-migrate
  labels: {{- include "keel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      labels: {{- include "keel.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.migrateImage.repository }}:{{ .Values.migrateImage.tag }}"
          command: ["sh", "/app/docker/migrate-entrypoint.sh"]
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
