{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "keel.fullname" .) }}
  labels: {{- include "keel.labels" . | nindent 4 }}
{{- end }}
